production:
  solr:
    hostname: localhost
    # port: 8983
    port: 8080
    log_level: WARNING
    solr_home: solr
    path: /solr/production
development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    solr_home: solr
    path: /solr/development
test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    solr_home: solr/test